---
platform: van1
instrument: Aeris_N2O_CO
type: simpleSerial
queue:
  name: "/dev-measurements"
  max_msg_size: 8000
  max_msgs: 50
connection: serial
command_queue:
  name: "/AERIS_N2O_CO_command"
  max_msg_size: 200
  max_msgs: 30
response_queue:
  name: "/AERIS_N2O_CO_response"
  max_msg_size: 200
  max_msgs: 30
response_header: " "
serial:
  device: "/dev/usb_serial_AERIS_N2O_CO"
  baud: 9600
measurement_delay_secs: 0 
stream:
  line_delimiter: "\r\n"
  item_delimiter: ","
  items: "inst_datetime,Inlet_Number,P,T0,T1,T2,T5,Tgas,CO,H2O,N2O,amb_T,amb_P,latitude,longitude"
  formats: "%m/%d/%Y %H:%M:%S.%f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,x,x" 
  units: "datetime,count,mbar,deg_c,deg_c,deg_c,deg_c,deg_c,ppm,ppm,ppb,deg_c,torr,lat,lon"
  acqTypes: "inst_datetime,engineering,engineering,engineering,engineering,engineering,engineering,engineering,measurement_calibrated,measurement_calibrated,measurement_calibrated,engineering,engineering,GPS,GPS"
  
logs:
  log_dir: "/home/vandaq/vandaq/acquirer/log"
  log_file: "acquirer_Aeris_N2O_CO.log"
  log_level: "INFO"
  logger_name: "Aeris_N2O_CO"

alarms:
  P:
    - value_<: 
        value: 135
        alarm_level: alarm
        alarm_type: underrange
        alarm_message: "Pressure below 135 mbar"
        impacts_data: true
    - value_>:
        value: 145 
        alarm_level: alarm
        alarm_type: overrange
        alarm_message: "Pressure above 145 mbar"
        impacts_data: true
  CO:
    - value_<: 
        value: 0
        alarm_level: alarm
        alarm_type: underrange
        alarm_message: "CO concentration is below zero"
        impacts_data: true
  N2O:
    - value_<: 
        value: 0
        alarm_level: alarm
        alarm_type: underrange
        alarm_message: "N2O concentration is below zero"
        impacts_data: true
  T2:
    - value_<: 
        value: 35
        alarm_level: alarm
        alarm_type: underrange
        alarm_message: "T2 is below 35 deg C"
        impacts_data: true
  Inlet_Number:
    - value_!=: 
        value: 0
        alarm_level: alarm
        alarm_type: wrong_value
        alarm_message: "Inlet_Number is not 0"
        impacts_data: true
