---
platform: van1
instrument: Aeris_CH4_C2H6
type: simpleSerial
queue:
  name: "/dev-measurements"
  max_msg_size: 8000
  max_msgs: 50
command_queue:
  name: "/AERIS_CH4_command"
  max_msg_size: 200
  max_msgs: 30
response_queue:
  name: "/AERIS_CH4_response"
  max_msg_size: 200
  max_msgs: 30
response_header: " "
connection: serial
serial:
  device: "/dev/usb_serial_AERIS_CH4_C2H6"
  baud: 9600
measurement_delay_secs: 0 
stream:
  line_delimiter: "\r\n"
  item_delimiter: ","
  items: "inst_datetime,Inlet_Number,P,T0,T1,T2,T5,Tgas,CH4,H2O,C2H6,R,x,TEC_sink_temp,Wall_Code,x,x"
  formats: "%m/%d/%Y %H:%M:%S.%f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,x,x" 
  units: "datetime,count,mbar,deg_c,deg_c,deg_c,deg_c,deg_c,ppm,ppm,ppb,const,ratio,deg_c,count,x,x"
  acqTypes: "inst_datetime,engineering,engineering,engineering,engineering,engineering,engineering,engineering,measurement_calibrated,measurement_calibrated,measurement_calibrated,engineering,measurement_calibrated,engineering,engineering,x,x"
  
logs:
  log_dir: "/home/vandaq/vandaq/acquirer/log"
  log_file: "acquirer_Aeris_CH4_C2H6.log"
  log_level: "INFO"
  logger_name: "Aeris_CH4_C2H6"

alarms:
  P:
    - value_<: 
        value: 235  
        alarm_level: alarm
        alarm_type: underrange
        alarm_message: "Pressure below 235 mbar"
        impacts_data: true
    - value_>:
        value: 245  
        alarm_level: alarm
        alarm_type: overrange
        alarm_message: "Pressure above 245 mbar"
        impacts_data: true
  CH4:
    - value_<: 
        value: 1.9  
        alarm_level: alarm
        alarm_type: underrange
        alarm_message: "CH4 concentration is below 1.9 ppm"
        impacts_data: true
  C2H6:
    - value_<: 
        value: 0  
        alarm_level: alarm
        alarm_type: underrange
        alarm_message: "C2H6 concentration is below 0 ppm"
        impacts_data: true
  T2:
    - value_>: 
        value: 30
        alarm_level: alarm
        alarm_type: overrange
        alarm_message: "T2 is above 30 deg C"
        impacts_data: true
  Inlet_Number:
    - value_!=: 
        value: 0
        alarm_level: alarm
        alarm_type: wrong_value
        alarm_message: "Inlet_Number is not 0"
        impacts_data: true
